language: c
addons:
  apt:
    packages:
      - libevent-dev
      - python-docutils
compiler:
  - clang
  - gcc
script:
  - ./autogen.sh
  - ./configure --enable-cassert --enable-werror --with-pam
  - make
  - make dist
